version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
    expose:
      - "5433"
    command: -p 5433

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5433

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev

    ports:
      - "3000:3000"

    volumes:
      - /app/node_modules
      - ./frontend:/app


